import React, { useState } from "react";
import { Form, Formik } from "formik";
import { openNotificationSuccess } from "../../Components/Assets/Api/Api";
import CashReport from "./TableReports/CashReport";
import AssetLiabilitiesReport from "./TableReports/AssetLiabilitiesReport";
import { scroller } from "react-scroll";
import CashFlowReportOptions from "../CashFlowOptions/CashFlowReportOptions";

const CashFlowReport = () => {
  let initialValues = {
    category: "",
  };

  const [showFilters, setShowFilters] = useState(false);
  const [step, setStep] = useState(0);

  let onSubmit = (values, resetForm) => {};

  const [inflow, setInflow] = useState([
    {
      type: "Salary Income",
      year1: "$908,223",
      year2: "$908,223",
      year3: "$908,223",
      year4: "$908,223",
      year5: "$908,223",
      year6: "$908,223",
      year7: "$908,223",
      year8: "$908,223",
      year9: "$908,223",
      year10: "$908,223",
    },
    {
      type: "Other Taxable income",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Net Business Income",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Net Income From Business (Coy & Trust)",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Other Non-Taxable income",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Rental Income",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Investment Income",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Interest Income",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Trust Distributions",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Family Tax Payments (A & B)",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Centrelink Payments",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Child Maintenance Received",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Super Pensions",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Annuity Income",
      year1: "$12",
      year2: "$13",
      year3: "$13",
      year4: "$14",
      year5: "$15",
      year6: "$0",
    },
    {
      type: "Lumpsum Super & Pension W/Drawals",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Investment Redemptions",
      year1: "$881,232",
      year2: "$81",
      year3: "$81",
      year4: "$81",
      year5: "$81",
      year6: "$81",
    },
    {
      type: "Loan Additions",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Other Lumpsum Additions",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Total Inflows",
      year1: "$881,244",
      year2: "$13",
      year3: "$13",
      year4: "$14",
      year5: "$15",
      year6: "$223",
    },
  ]);

  const [outFlow, setOutFlow] = useState([
    {
      type: "General Living Expenses",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Holidays",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Otder Expenses",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Personal Insurances",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Education Expenses",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Child Maintenance Payed",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Other Lumpsum Purchases",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Property Expenses",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Non-Deductible Loan Repayments",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Loan Repayments (Property Loans)",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Investment Loan Repayments",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Additional Purchases of Investments",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Tax",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Concessional Super Contributions",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Non-Concessional Super Contributions",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Total Inflows",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
  ]);

  const [surplus, setSurplus] = useState([
    {
      type: "Surplus/Deficit",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Home Loan End",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Cash Savings Year End",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
  ]);

  const [clientData, setClientData] = useState([
    {
      type: "Age",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Gross Employment Income",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Other taxable Income",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Investment Income(Shares & Mgd Funds)",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Interest Income",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Other Investment Income",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Franking Credits",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Capital Gains Tax",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Rental Income",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Net Trust Distribution",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Centrelink",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Annuity Income",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Lifetime Pension",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Super Pension",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Total Assessable income",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Deductible Superannuation Contributions",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Other Deductible Expenses",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Deductible interest Costs",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Income Protection Insurance",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Annuity Deductible Amount",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Lifetime Pension",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Tax Free Pension Amount",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Total Allowable Deductions",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Total Taxable Income",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Basic Tax payable",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Budget Repair Levy",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Medicare levy",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Medicare Levy Surcharge",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Total Tax payable",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "15% Pension Rebate",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "10% Pension Rebate",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Spouse Super Rebate",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "SAPTO",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "30% Rebate for insurance Bonds",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "LITO",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Total Rebates",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Franking Credits",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Total Tax payable",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Reportable Fringe Benefits",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Unused SAPTO",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Additional Contributions Tax",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
  ]);

  const [asset, setAssets] = useState([
    {
      type: "Lifestyle Assets",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Family Home",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Direct Share Portfolios",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Managed Funds",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Other Investments",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Cash",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Term Deposits",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Insurance Bonds",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Investment Properties",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Superannuation",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Account Based Pensions",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Annuity Investments",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Trading Company",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Business Trust",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "SMSF Net Assets",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Family Trust Net Assets",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Total Assets",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      isHeader: true,
      type: "Liabilities ", // This will act like a sub-header inside tbody
    },
  ]);

  const [assetsTestPensionAllowance, setAssetsTestPensionAllowance] = useState([
    {
      type: "Personal Assets",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Lynda Financial Assets",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "abc Financial Assets",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Lynda Superannuation",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "abc Superannuation",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Lynda Pension Assets",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "abc Pension Assets",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Lynda Annuity",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "abc Annuity",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Rental Properties",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Trading Company Net Assets",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Business Trust Net Assets",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Family Trust Net Assets",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Investment Loans",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Investment Property Loan",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Total Assets",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Lower - Pensions",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Lower - Allowance",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Upper",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Excess Assets",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
  ]);

  const [incomeTestPensionsAllowances, setIncomeTestPensionsAllowances] =
    useState([
      {
        type: "Deemed Financial Income",
        existing: "$0",
        year1: "$0",
        year2: "$0",
        year3: "$0",
        year4: "$0",
        year5: "$0",
        year6: "$0",
      },
      {
        type: "Net Rental Income",
        existing: "$0",
        year1: "$0",
        year2: "$0",
        year3: "$0",
        year4: "$0",
        year5: "$0",
        year6: "$0",
      },
      {
        type: "Trust Distributions & Company Income",
        existing: "$0",
        year1: "$0",
        year2: "$0",
        year3: "$0",
        year4: "$0",
        year5: "$0",
        year6: "$0",
      },
      {
        type: "Lynda Salary Income",
        existing: "$0",
        year1: "$0",
        year2: "$0",
        year3: "$0",
        year4: "$0",
        year5: "$0",
        year6: "$0",
      },
      {
        type: "abc Salary Income",
        existing: "$0",
        year1: "$0",
        year2: "$0",
        year3: "$0",
        year4: "$0",
        year5: "$0",
        year6: "$0",
      },
      {
        type: "Lynda Other Income",
        existing: "$0",
        year1: "$0",
        year2: "$0",
        year3: "$0",
        year4: "$0",
        year5: "$0",
        year6: "$0",
      },
      {
        type: "abc Other Income",
        existing: "$0",
        year1: "$0",
        year2: "$0",
        year3: "$0",
        year4: "$0",
        year5: "$0",
        year6: "$0",
      },
      {
        type: "Lynda Pension Income",
        existing: "$0",
        year1: "$0",
        year2: "$0",
        year3: "$0",
        year4: "$0",
        year5: "$0",
        year6: "$0",
      },
      {
        type: "abc Pension Income",
        existing: "$0",
        year1: "$0",
        year2: "$0",
        year3: "$0",
        year4: "$0",
        year5: "$0",
        year6: "$0",
      },
      {
        type: "Lynda Annuity Income",
        existing: "$0",
        year1: "$0",
        year2: "$0",
        year3: "$0",
        year4: "$0",
        year5: "$0",
        year6: "$0",
      },
      {
        type: "abc Annuity Income",
        existing: "$0",
        year1: "$0",
        year2: "$0",
        year3: "$0",
        year4: "$0",
        year5: "$0",
        year6: "$0",
      },
      {
        type: "Less",
        existing: "$0",
        year1: "$0",
        year2: "$0",
        year3: "$0",
        year4: "$0",
        year5: "$0",
        year6: "$0",
      },
      {
        type: "Lynda Deductible Pension Income",
        existing: "$0",
        year1: "$0",
        year2: "$0",
        year3: "$0",
        year4: "$0",
        year5: "$0",
        year6: "$0",
      },
      {
        type: "abc Deductible Pension Income",
        existing: "$0",
        year1: "$0",
        year2: "$0",
        year3: "$0",
        year4: "$0",
        year5: "$0",
        year6: "$0",
      },
      {
        type: "Lynda Work Bonus",
        existing: "$0",
        year1: "$0",
        year2: "$0",
        year3: "$0",
        year4: "$0",
        year5: "$0",
        year6: "$0",
      },
      {
        type: "abc Work Bonus",
        existing: "$0",
        year1: "$0",
        year2: "$0",
        year3: "$0",
        year4: "$0",
        year5: "$0",
        year6: "$0",
      },
      {
        type: "Total Income",
        existing: "$0",
        year1: "$0",
        year2: "$0",
        year3: "$0",
        year4: "$0",
        year5: "$0",
        year6: "$0",
      },
      {
        type: "Lower",
        existing: "$0",
        year1: "$0",
        year2: "$0",
        year3: "$0",
        year4: "$0",
        year5: "$0",
        year6: "$0",
      },
      {
        type: "Upper",
        existing: "$0",
        year1: "$0",
        year2: "$0",
        year3: "$0",
        year4: "$0",
        year5: "$0",
        year6: "$0",
      },
      {
        type: "Excess Income",
        existing: "$0",
        year1: "$0",
        year2: "$0",
        year3: "$0",
        year4: "$0",
        year5: "$0",
        year6: "$0",
      },
    ]);

  const [allowance, setAllowance] = useState([
    {
      type: "Total Income",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Lower",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Upper",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Partner Balance over",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
  ]);

  const [clientIncome, setClientIncome] = useState([
    {
      type: "Deemed Income",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Net Rental Income",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Trust Distributions & Company Income",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Salary Income",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Other Income",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Annuity Income",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Pension Income",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Less",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Deductible Pension Income",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Total Income",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
  ]);

  const [clientPayment, setClientPayment] = useState([
    {
      type: "Client",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Age",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Payment Amount",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Asset Test Reduction",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Under Asset Test",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Income Test Reduction",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Under Income Test",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Actual Payment",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
  ]);

  const [familyTaxBenefitPartA, setFamilyTaxBenefitPartA] = useState([
    {
      type: "Total Maximum rate of FTB- Part A",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Base Rate of FTB-Part A",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Total Adjusted Family Income",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
      rowGreen: "true",
    },
    {
      type: "Income Level For Maximum Rate of FTB-Part A",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Income Level For Base Rate of FTB-Part A",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Income Mantaince Free Area",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Total FTB- Part A (including Supplement)",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
  ]);

  const [liabilities, setLiabilities] = useState([
    {
      type: "Lifestyle Assets",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Other Investments",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Cash",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Term Deposits",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Insurance Bonds",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Investment Properties",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Superannuation",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Account Based Pensions",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Annuity Investments",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Trading Company",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Business Trust",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "SMSF Net Assets",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Family Trust Net Assets",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
    {
      type: "Total Assets",
      existing: "$0",
      year1: "$0",
      year2: "$0",
      year3: "$0",
      year4: "$0",
      year5: "$0",
      year6: "$0",
    },
  ]);

  return (
    <div className="container-fluid  ">
      <Formik
        initialValues={initialValues}
        onSubmit={onSubmit}
        enableReinitialize
      >
        {({ values, setFieldValue, handleChange, handleBlur, resetForm }) => {
          return (
            <Form>
              <div name="topSection">
                <CashFlowReportOptions step={step} setStep={setStep} />
              </div>

              <div className="px-0 px-md-4 reportSection">
                {step == 0 && (
                  <>
                    <CashReport
                      showFilters={showFilters}
                      setShowFilters={setShowFilters}
                      inflow={inflow}
                      outFlow={outFlow}
                      surplus={surplus}
                      clientData={clientData}
                      assetsTestPensionAllowance={assetsTestPensionAllowance}
                      incomeTestPensionsAllowances={
                        incomeTestPensionsAllowances
                      }
                      allowance={allowance}
                      clientIncome={clientIncome}
                      // partnerIncome={partnerIncome}
                      clientPayment={clientPayment}
                      familyTaxBenefitPartA={familyTaxBenefitPartA}
                      values={values}
                      setFieldValue={setFieldValue}
                    />
                  </>
                )}

                {step == 1 && (
                  <>
                    <AssetLiabilitiesReport
                      showFilters={showFilters}
                      setShowFilters={setShowFilters}
                      asset={asset}
                      setInflow={setInflow}
                      liabilities={liabilities}
                      setOutFlow={setOutFlow}
                      surplus={surplus}
                      setSurplus={setSurplus}
                      values={values}
                      setFieldValue={setFieldValue}
                    />
                  </>
                )}

                <div className="row justify-content-between px-2 my-5">
                  <button
                    className="btn btn-outline w-25 backBtn"
                    onClick={() => {
                      setStep(step - 1);
                      scroller.scrollTo("topSection", {
                        duration: 500,
                        delay: 0,
                        smooth: "easeInOutQuad",
                      });
                    }}
                  >
                    Back
                  </button>
                  <button
                    className="btn bgColor w-25 modalBtn"
                    onClick={() => {
                      setStep(step + 1);
                      scroller.scrollTo("topSection", {
                        duration: 500,
                        delay: 0,
                        smooth: "easeInOutQuad",
                      });
                    }}
                  >
                    Next
                  </button>
                </div>
              </div>
            </Form>
          );
        }}
      </Formik>
    </div>
  );
};

export default CashFlowReport;
